### ISSUE TITLE
Fix issue with duplicate key warning in footer

### ISSUE THREAD

**Issue by manojadams** [manojadams/metaforms-core#27]
### Detail

```
next-dev.js:20 Warning: Encountered two children with the same key, `previous`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Footer (webpack-internal:///./node_modules/@manojadams/metaforms-core/dist/index.modern.js:2864:66)
    at form
    at SectionForm (webpack-internal:///./node_modules/@manojadams/metaforms-core/dist/index.modern.js:3072:62)
    at Form (webpack-internal:///./node_modules/@manojadams/metaforms-core/dist/index.modern.js:3115:48)
```

**Comment by manojadams** [comment]
Fixed and tested.
